version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: simon@25!
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: simonmwangikangi@gmail.com
      PGADMIN_DEFAULT_PASSWORD: simon@25!
    ports:
      - "5050:80"
    networks:
      - mynetwork

networks:
  mynetwork:
